# Explicit dependency list; no applications or machine inventory.
brew "git"
brew "gitleaks"
brew "pre-commit"
brew "vim"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "ruff"
brew "llvm"
brew "markdownlint-cli"
brew "prettier"
