# Explicit dependency list; no applications or machine inventory.
# Git and Vim use the versions provided by macOS.
brew "stow"
brew "uv"
brew "git-delta"
brew "gitleaks"
brew "pre-commit"
brew "tmux"
brew "zoxide"
brew "direnv"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "ruff"
brew "llvm"
brew "markdownlint-cli"
brew "prettier"
